version: '3.3'

services:
  drupal_db:
    image: mysql:5.7
    volumes: ['mysql_db:/var/lib/mysql']
    restart: always
    networks: ['mynet']
    environment:
      ['MYSQL_ROOT_PASSWORD:redhat',
      'MYSQL_USER:yash',
      'MYSQL_PASSWORD:docker',
      'MYSQL_DATABASE:drupaldb']



  mydrupal:
    image: drupal:latest
    restart: always
    networks: [mynet]
    ports: ['1234:80']
    environment:
      ['MYSQL_DATABASE:drupaldb',
      'MYSQL_USER:yash',
      'MYSQL_PASSWORD:docker',
      'MYSQL_ROOT_PASSWORD:redhat']
    volumes: 
        ['d_modules:/var/www/html/modules',
        'd_profiles:/var/www/html/profiles',
        'd_sites:/var/www/html/sites',
        'd_themes:/var/www/html/themes']


    
networks:
  mynet:        


volumes:
  mysql_db:
  d_modules:
  d_profiles:
  d_sites:
  d_themes:

